#MQTT CLIENT CONFIGURATIONS
clientSub:
  clientId: "cg_subscriber"
  serverAddress: "tcp://test.mosquitto.org:1883"
  qos: 1
  connectionTimeout: 1
  writeTimeout: 1
  keepAlive: 10
  pingTimeout: 1
  connectRetry: true
  autoConnect: true
  orderMaters: false

clientPub:
  clientId: "cg_publisher"
  serverAddress: "tcp://localhost:1883"
  qos: 1
  connectionTimeout: 1
  writeTimeout: 1
  keepAlive: 10
  pingTimeout: 1
  connectRetry: true
  autoConnect: true
  orderMaters: false  

#LOGS
logs:
  subPayload: true
  debug: false
  warning: false
  error: false
  critical: false

#TOPICS TO SUBSCRIBE TO
topicsSub:
  topic:
    - "/cg-playground/sample/1"
    - "/cg-playground/sample/2"
    - "/cg-playground/sample/3"


#TOPICS TO PUBLISH TO
topicsPub:
  topic:
    - "/cg-playground/sample/11"
    - "/cg-playground/sample/12"
    - "/cg-playground/sample/13"