version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - type: bind
        source: ./config
        target: /mosquitto/config
        read_only: true
      - type: bind
        source: ./data
        target: /mosquitto/data
      - type: bind
        source: ./log
        target: /mosquitto/log